import type { MODALITY_OPTIONS } from "@/shared/constants/modality";

export interface BackendAvailabilityBlockResponse {
  availabilityBlockId: string;
  date: string;
  startTime: string;
  endTime: string;
  repeatWeekly: boolean;
  autoGenerated: boolean;
}

export interface BackendBookingResponse {
  bookingId: string;
  sessionDate: string;
  startTime: string;
  endTime: string;
  modality: typeof MODALITY_OPTIONS[number];
  tutorSubjectName: string;
  studentFullName: string;
}

export interface BackendWeeklyScheduleResponse {
  from: string;
  to: string;
  availabilityBlocks: BackendAvailabilityBlockResponse[];
  bookings: BackendBookingResponse[];
}
