import { AvailabilityBlockRequest } from "@/modules/tutor/availability/interfaces/requests/availability-block.interface";

export interface AvailabilityBlockResponse extends AvailabilityBlockRequest {
  availabilityBlockId: string;
  autoGenerated: boolean;
}