import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useAvailabilityBlocks } from "@/modules/tutor/availability/hooks/useAvailabilityBlocks";
import { useSaveAvailabilityBlocks } from "@/modules/tutor/availability/hooks/useSaveAvailabilityBlocks";
import {
  getCurrentWeekMonday,
  getWeekEnd,
  toDateStr,
  isBeforeNow,
  getEarliestSelectableTime,
  normalizeBlocks,
} from "@/modules/tutor/availability/utils/availability.utils";
import { useWeekCustomization } from "@/modules/tutor/availability/hooks/useWeekCustomization";
import { useRemoveWeekCustomization } from "@/modules/tutor/availability/hooks/useRemoveWeekCustomization";
import type { AvailabilityBlockRequest } from "@/modules/tutor/availability/interfaces/requests/availability-block.interface";

interface DraftBlock {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
}

const FETCH_WEEKS_AHEAD = 12;

export function useAvailabilityDraft() {
  const MIN_BLOCK_DURATION_MS = 60 * 60 * 1000;
  const currentMonday = useMemo(() => getCurrentWeekMonday(), []);

  const [viewedMonday, setViewedMonday] = useState(currentMonday);
  const viewedWeekEnd = useMemo(() => getWeekEnd(viewedMonday), [viewedMonday]);

  const fetchFrom = toDateStr(currentMonday);
  const fetchTo = useMemo(() => {
    const base = new Date(currentMonday);
    base.setDate(base.getDate() + FETCH_WEEKS_AHEAD * 7);

    // El rango fijo (12 semanas desde HOY) no alcanza si el tutor navega más allá de esa
    // ventana. Si la semana que se está viendo cae más lejos, extendemos el rango para
    // que siempre la cubra — además con margen suficiente para traer también las copias
    // de repetición que se generen desde esa semana hacia adelante (mismo horizonte que
    // usa el backend, REPEAT_WEEKS_AHEAD).
    const viewedEndWithBuffer = new Date(viewedWeekEnd);
    viewedEndWithBuffer.setDate(viewedEndWithBuffer.getDate() + FETCH_WEEKS_AHEAD * 7);

    return toDateStr(base > viewedEndWithBuffer ? base : viewedEndWithBuffer);
  }, [currentMonday, viewedWeekEnd]);

  const { data: allBlocks, isLoading } = useAvailabilityBlocks(fetchFrom, fetchTo);
  const { mutate: save, isPending } = useSaveAvailabilityBlocks();

  const [draftBlocks, setDraftBlocks] = useState<DraftBlock[] | null>(null);
  const [repeatWeekly, setRepeatWeekly] = useState<boolean | null>(null);
  const [isConfirmDialogOpen, setIsConfirmDialogOpen] = useState(false);

  const viewedWeekStartStr = toDateStr(viewedMonday);
  const viewedWeekEndStr = toDateStr(viewedWeekEnd);

  // Bloques existentes SOLO de la semana que se está viendo (el resto del rango fetcheado
  // se usa nada más para saber si hay repetición activa en semanas futuras, no se muestra acá)
  const existingWeekBlocks = useMemo(
    () =>
      (allBlocks ?? []).filter((b) => b.date >= viewedWeekStartStr && b.date <= viewedWeekEndStr),
    [allBlocks, viewedWeekStartStr, viewedWeekEndStr]
  );

  const initialRepeatWeekly = existingWeekBlocks[0]?.repeatWeekly ?? false;
  const effectiveRepeatWeekly = repeatWeekly ?? initialRepeatWeekly;

  const blocks =
    draftBlocks ??
    existingWeekBlocks.map((b) => ({
      id: b.availabilityBlockId,
      date: b.date,
      startTime: b.startTime,
      endTime: b.endTime,
    }));

  const originalSignature = useMemo(
    () => normalizeBlocks(existingWeekBlocks),
    [existingWeekBlocks]
  );
  const currentSignature = useMemo(() => normalizeBlocks(blocks), [blocks]);

  const hasChanges =
    currentSignature !== originalSignature || effectiveRepeatWeekly !== initialRepeatWeekly;

  const earliestSelectable = useMemo(() => getEarliestSelectableTime(), []);
  const todayStr = useMemo(() => toDateStr(new Date()), []);
  const earliestSelectableStr = useMemo(() => toDateStr(earliestSelectable), [earliestSelectable]);

  const events = useMemo(() => {
    const drawnBlocks = blocks.map((b) => ({
      id: b.id,
      start: `${b.date}T${b.startTime}`,
      end: `${b.date}T${b.endTime}`,
      display: "block",
    }));

    const isViewingCurrentWeek = todayStr >= viewedWeekStartStr && todayStr <= viewedWeekEndStr;
    const staysOnSameDay = earliestSelectableStr === todayStr;

    if (!isViewingCurrentWeek || !staysOnSameDay) {
      return drawnBlocks;
    }

    return [
      ...drawnBlocks,
      {
        start: `${todayStr}T00:00:00`,
        end: `${todayStr}T${earliestSelectable.toTimeString().slice(0, 8)}`,
        display: "background",
        classNames: ["fc-unavailable-now"],
      },
    ];
  }, [
    blocks,
    todayStr,
    earliestSelectableStr,
    earliestSelectable,
    viewedWeekStartStr,
    viewedWeekEndStr,
  ]);

  const { data: weekCustomization } = useWeekCustomization(viewedWeekStartStr);
  const { mutate: removeCustomization, isPending: isRemovingCustomization } =
    useRemoveWeekCustomization();

  // Solo mostrar el banner si existe al menos un bloque auto-generado (hay horario habitual activo)
  const hasAutoGeneratedBlocks = (allBlocks ?? []).some((b) => b.autoGenerated);
  const isWeekCustomized = (weekCustomization?.customized ?? false) && hasAutoGeneratedBlocks;

  const [isClearConfirmOpen, setIsClearConfirmOpen] = useState(false);

  const isInheritedRepeat =
    existingWeekBlocks.length > 0 && existingWeekBlocks.every((b) => b.autoGenerated);

  function requestClearWeek() {
    setIsClearConfirmOpen(true);
  }

  function confirmClearWeek() {
    setIsClearConfirmOpen(false);

    const payload: AvailabilityBlockRequest[] = [];

    save(
      { weekStart: viewedWeekStartStr, weekEnd: viewedWeekEndStr, blocks: payload },
      {
        onSuccess: () => {
          setDraftBlocks(null);
          setRepeatWeekly(null);
        },
      }
    );
  }

  function cancelClearWeek() {
    setIsClearConfirmOpen(false);
  }

  function handleDatesSet(rangeStart: Date) {
    setViewedMonday((prev) => (toDateStr(prev) === toDateStr(rangeStart) ? prev : rangeStart));
    // al cambiar de semana, se descarta cualquier draft sin guardar de la semana anterior
    setDraftBlocks(null);
    setRepeatWeekly(null);
  }

  function selectAllow(selectInfo: { start: Date; end: Date }): boolean {
    return (
      selectInfo.start.toDateString() === new Date(selectInfo.end.getTime() - 1).toDateString()
    );
  }

  function addDraftBlock(start: Date, end: Date): boolean {
    if (isBeforeNow(start)) {
      toast.error("No podés seleccionar un horario que ya pasó.");
      return false;
    }

    if (end.getTime() - start.getTime() < MIN_BLOCK_DURATION_MS) {
      toast.error("Los bloques deben tener una duración mínima de 1 hora.");
      return false;
    }

    const newBlock: DraftBlock = {
      id: typeof crypto?.randomUUID === "function" ? crypto.randomUUID() : String(Date.now()),
      date: toDateStr(start),
      startTime: start.toTimeString().slice(0, 8),
      endTime: end.toTimeString().slice(0, 8),
    };

    setDraftBlocks((prev) => [...(prev ?? blocks), newBlock]);
    return true;
  }

  function removeDraftBlock(blockId: string) {
    setDraftBlocks((prev) => (prev ?? blocks).filter((b) => b.id !== blockId));
  }

  function saveAvailability() {
    const payload: AvailabilityBlockRequest[] = blocks.map((b) => ({
      date: b.date,
      startTime: b.startTime,
      endTime: b.endTime,
      repeatWeekly: effectiveRepeatWeekly,
    }));

    save(
      { weekStart: viewedWeekStartStr, weekEnd: viewedWeekEndStr, blocks: payload },
      {
        onSuccess: () => {
          setDraftBlocks(null);
          setRepeatWeekly(null);
        },
      }
    );
  }

  function requestSave() {
    if (effectiveRepeatWeekly) {
      setIsConfirmDialogOpen(true);
      return;
    }
    saveAvailability();
  }

  function confirmSave() {
    setIsConfirmDialogOpen(false);
    saveAvailability();
  }

  function cancelSave() {
    setIsConfirmDialogOpen(false);
    setRepeatWeekly(null);
  }

  function removeWeekCustomization() {
    removeCustomization(viewedWeekStartStr);
  }

  return {
    isLoading,
    isPending,
    currentMondayStr: toDateStr(currentMonday),
    events,
    hasChanges,
    effectiveRepeatWeekly,
    repeatWeeksAhead: FETCH_WEEKS_AHEAD,
    setRepeatWeekly,
    selectAllow,
    addDraftBlock,
    removeDraftBlock,
    handleDatesSet,
    isConfirmDialogOpen,
    requestSave,
    confirmSave,
    cancelSave,
    isWeekCustomized,
    isRemovingCustomization,
    removeWeekCustomization,
    isClearConfirmOpen,
    requestClearWeek,
    confirmClearWeek,
    cancelClearWeek,
    isInheritedRepeat,
  };
}
